### ISSUE TITLE
ignore.synchronization=true/ browser.waitforAngularEnabled(true) takes so long when compared to browser.sleep()

### ISSUE THREAD

**Issue by sindhuk20** [hetznercloud/protractor-test-helper#37]

**Comment by wachri** [comment]
@sindhuk20 Can you please add description and explain where do you see a bug or problem in this library? All mentioned functionality is part of protractor it self...

**Comment by sindhuk20** [comment]
@wachri while executing e2e tests in protractor when we are using ignore.synchronization=true/ browser.waitforAngularEnabled(true) to handle waits is too slow when compared to browser.sleep(10000) to proceed to next step. How to address these kind of wait issues to make the script execution faster

**Comment by wachri** [comment]
@sindhuk20 can you please ask your questions on https://stackoverflow.com/?
