### ISSUE TITLE
Handle inconsistent wait issues for angular applications using protractor jasmine

### ISSUE THREAD

**Issue by sindhuk20** [hetznercloud/protractor-test-helper#38]

**Comment by wachri** [comment]
@sindhuk20 Can you please add a description and explain where do you see a bug or problem in this library?

**Comment by sindhuk20** [comment]
I am beginner for protractor and jasmine, working on angular based application. While executing e2e tests, the test scripts are failing inconsistently. So we used ignore.synchronized = true to avoid the inconsistency. But it is taking nearly one to two minutes to execute the next step in the test scripts. Could you please help us on this to reduce the time duration taken to click next element.

**Comment by wachri** [comment]
@sindhuk20 can you please ask your questions on https://stackoverflow.com/?
